version: "3"
services:
  share_dive:
    networks:
      - home
      - default
    image: node:12
    command: >
      bash -c "
        npm install &&
        npm run run
      "
    restart:
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
    volumes:
    - .:/share_drive

networks:
  home:
