version: "3"
services:
  share_dive:
    build: .
    command: >
      bash -c "
        npm run start
      "
    networks:
      - home
      - default
    restart: always
    environment:
      TZ: Asia/Tokyo
      PORT: 8010
    volumes:
    - .:/share_drive
    ports:
    - "8070:8010"

networks:
  home:
    external: true
