version: "3"
services:
  share_dive:
    image: node:12
    command: >
      bash -c "
        npm install &&
        npm run run
      "
    networks:
      - home
      - default
    restart: always
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
    working_dir:
      /share_drive
    volumes:
    - .:/share_drive

networks:
  home:
    external: true
