version: "3"
services:
  sharedrive:
    build: .
    command: >
      bash -c "
        npm i &&
        npm run start
      "
    networks:
      - home
      - default
    restart: always
    environment:
      TZ: Asia/Tokyo
      PORT: 5000
    volumes:
    - .:/share_drive

networks:
  home:
    external: true
